config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
  f_aliases:
    src: aliases
    dst: ~/.aliases
profiles:
  Jimmys-MacBook-Air.local:
    dotfiles:
    - f_zshrc
    - f_vimrc
    - f_init.vim
    - d_oh-my-zsh
    - f_aliases
